### ISSUE TITLE
docker-compose doesn't work

### ISSUE THREAD

**Issue by hadusam** [blue-oil/blueoil#1084]
```
masuda@leapmind-server-26:~/Project/hadusam/blueoil$ docker-compose run blueoil init
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/python3.6/bin/blueoil", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/pyenv/versions/3.6.10/envs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3261, in <module>
    @_call_aside
  File "/usr/local/pyenv/versions/3.6.10/envs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.6.10/envs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/pyenv/versions/3.6.10/envs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/pyenv/versions/3.6.10/envs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/pyenv/versions/3.6.10/envs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'blueoil' distribution was not found and is required by the application
```

**Comment by iizukak** [comment]
Wow, thank you for the reporting.
