### ISSUE TITLE
Incompatible version `absl-py`

### ISSUE THREAD

**Issue by Suikaba** [blue-oil/blueoil#1167]
There exists a dependency error of `absl-py` in the current blueoil (964c64b).

Following tutorials, I have run a docker command like this:
```
docker run --rm -it \
     -v $(pwd)/cifar:/home/blueoil/cifar \
     -v $(pwd)/config:/home/blueoil/config \
     blueoil_$(id -un):v0.27.0-1-g964c64b \
     blueoil init -o config/cifar10_test.py
```

Then this error occured:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (absl-py 0.9.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('absl-py<0.9,>=0.7'), {'tensorflow-metadata'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/blueoil", line 33, in <module>
    sys.exit(load_entry_point('blueoil', 'console_scripts', 'blueoil')())
  File "/usr/local/bin/blueoil", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/blueoil/blueoil/cmd/main.py", line 21, in <module>
    from blueoil.cmd.convert import convert as run_convert
  File "/home/blueoil/blueoil/cmd/convert.py", line 20, in <module>
    from blueoil.cmd.export import DEFAULT_INFERENCE_TEST_DATA_IMAGE, run as run_export
  File "/home/blueoil/blueoil/cmd/export.py", line 22, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 102, in <module>
    from tensorflow_core import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1007, in _handle_fromlist
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3251, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 597, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (absl-py 0.9.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('absl-py<0.9,>=0.7'), {'tensorflow-metadata'})
```

PR https://github.com/blue-oil/blueoil/pull/1151 may be related this issue.

**Comment by Suikaba** [comment]
Now, `blueoil init` command works correctly. Thanks @oatawa1 and @iizukak !
