### ISSUE TITLE
Can't convert split from batchnorm network

### ISSUE THREAD

**Issue by ruimashita** [blue-oil/blueoil#187]
Raise error:
```
Traceback (most recent call last):
  File "./blueoil/blueoil_convert.py", line 184, in <module>
    main()
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./blueoil/blueoil_convert.py", line 180, in main
    run(experiment_id, restore_path)
  File "./blueoil/blueoil_convert.py", line 148, in run
    cache_dma=cache_dma
  File "/home/blueoil/dlk/python/dlk/scripts/generate_project.py", line 149, in run
    optimize_graph_step(model, config)
  File "/home/blueoil/dlk/python/dlk/scripts/generate_project.py", line 61, in optimize_graph_step
    pass_pack_weights(graph)
  File "/home/blueoil/dlk/python/dlk/core/optimizer.py", line 410, in pass_pack_weights
    exec_list = [n for n in sort_graph(graph) if n.op_type == 'Conv']
  File "/home/blueoil/dlk/python/dlk/core/graph_pattern_matching.py", line 47, in sort_graph
    top_order(node, exec_list, visited)
  File "/home/blueoil/dlk/python/dlk/core/graph_pattern_matching.py", line 69, in top_order
    top_order(input_node, exec_list, visited)
  File "/home/blueoil/dlk/python/dlk/core/graph_pattern_matching.py", line 66, in top_order
    if visited[output_node.name]:
KeyError: 'second_BatchNorm_FusedBatchNorm'

```

pb file: https://drive.google.com/a/leapmind.io/file/d/1Hn123979HGFVqPsN_L9FHwa-s5jfAb-3/view?usp=sharing

github branch: https://github.com/ruimashita/blueoil/tree/split_from_bn
network file: https://github.com/ruimashita/blueoil/blob/split_from_bn/lmnet/lmnet/networks/classification/split_from_bn.py

**Comment by tvlenin** [comment]
Hi @ruimashita,
Do you have any update about this error? I have a similar error but with convolution layers.
