### ISSUE TITLE
run.py raise SystemError on object detection task

### ISSUE THREAD

**Issue by ruimashita** [blue-oil/blueoil#203]
commit: https://github.com/blue-oil/blueoil/commit/9069945928fbc985fadf546d7a4e2008709ed83a

Error:
```  
$ python run.py -m ../models/lib/lib_x86.so  -c ../models/meta.yaml -i ~/lmnet/tests/fixtures/cat.jpg
Output: (before post process)
[[[[ 4.16990221e-02  1.21459290e-01  4.14416373e-01 -3.92589606e-02
     2.53661536e-02 -2.88744837e-01 -3.89133058e-02 -2.03904375e-01
     4.52421546e-01 -6.23153569e-03 -9.69785377e-02 -2.23556563e-01
     3.36957693e-01 -7.29453921e-01  1.93570912e-01  1.31687587e-02
     1.32422656e-01 -3.15151483e-01 -4.15708944e-02 -4.00289267e-01
     2.02673823e-01  3.74822080e-01 -2.79635727e-01 -6.59043193e-02
    -3.49321961e-02 -3.00489634e-01  1.25380293e-01 -4.38977569e-01
    -1.85146123e-01  7.76409954e-02]
   [-3.82962644e-01  1.89095557e-01  3.41529429e-01  1.10425927e-01
     4.49382290e-02 -1.49093881e-01 -3.88808697e-02 -3.01358074e-01
    -1.18894175e-01 -3.89587194e-01  2.96067566e-01  5.94569258e-02
     5.46231627e-01 -6.42969847e-01 -2.17220008e-01  3.02997157e-02
    -1.52833283e-01 -2.84683287e-01 -1.00926667e-01 -3.35364461e-01
    -5.82846761e-01  2.40954235e-01  1.36920393e-01  1.68624431e-01
    -5.35118639e-01 -3.20932537e-01 -6.13880926e-04 -6.41059220e-01
     1.51103493e-02 -1.82194650e-01]
   [ 1.77498952e-01 -3.16580106e-03 -5.00306711e-02  1.19161904e-01
     1.43895686e-01  4.89279889e-02  7.77697042e-02 -6.28883660e-01
    -1.01970166e-01  6.66012391e-02 -1.22509331e-01 -2.94972897e-01
     5.55538654e-01 -1.65248692e-01  1.15461297e-01  2.79018015e-01
     7.75546506e-02 -3.64125557e-02  1.30125061e-01 -5.53100049e-01
     9.14715230e-02  4.96715367e-01 -1.96437761e-02 -1.30945802e-01
    -3.28419119e-01 -6.56322122e-01 -2.44320780e-01 -1.95851490e-01
    -4.11249906e-01 -4.24262047e-01]
   [-2.87276447e-01  2.33305380e-01  4.80535068e-03  3.82405996e-01
    -1.67419419e-01 -5.52443378e-02 -1.07319996e-01  1.90779626e-01
    -3.03715114e-02 -7.57871717e-02  2.98998564e-01 -4.85548168e-01
     5.91106057e-01 -6.99805200e-01 -3.76595616e-01 -2.77219802e-01
     1.36357863e-02 -8.02089199e-02 -6.25561876e-03 -3.02171847e-03
    -2.93629736e-01  2.49332473e-01  2.48164773e-01 -1.74078912e-01
    -1.70801669e-01 -9.27327275e-02  1.10893868e-01 -8.02588761e-02
    -3.22064221e-01 -6.25340343e-01]]

  [[-1.41661137e-01 -2.25361735e-01  1.60395786e-01  4.31035638e-01
     2.26715803e-01  2.86333650e-01 -1.01220876e-01 -2.37492681e-01
     2.20321223e-01  4.25544232e-01  3.25798750e-01 -1.28115356e-01
     3.05699229e-01  2.83136308e-01  2.22951457e-01  8.12764168e-02
    -4.82360154e-01  1.19428448e-01 -5.24344683e-01 -5.71382761e-01
     3.51511985e-01 -8.71364549e-02  4.87667434e-02  2.91161269e-01
     2.74492383e-01 -2.23244548e-01 -2.85915375e-01 -2.06722274e-01
     4.09439087e-01 -1.56909660e-01]
   [-7.66852736e-01 -1.62735760e-01  5.04697263e-01  4.30337876e-01
     1.49268493e-01  8.62326920e-01  4.39791769e-01  1.07471474e-01
    -4.32256162e-01  3.54064375e-01  9.20385197e-02 -1.04564168e-01
     2.11690575e-01  9.16678607e-02  1.80912331e-01  6.90912455e-02
     8.93525928e-02 -9.23538581e-02  3.13893288e-01 -7.79607415e-01
     7.62903094e-01  2.83056319e-01  2.58337915e-01  8.14351216e-02
    -8.94407555e-02  1.74301952e-01 -4.55782026e-01 -1.94334030e-01
    -9.71817784e-03 -4.76580948e-01]
   [-5.05542904e-02  3.76715474e-02 -6.42348528e-02  3.03124249e-01
    -3.46815921e-02  5.99443018e-01 -1.08550578e-01 -1.36428207e-01
    -4.35354382e-01 -4.33430552e-01 -1.09625146e-01  4.70472313e-03
    -2.38124266e-01 -1.02748752e-01 -8.31042901e-02 -6.83565214e-02
     2.44552553e-01 -4.26750302e-01 -4.85301375e-01 -7.18888700e-01
     2.81403154e-01  1.81119457e-01 -6.98864534e-02  2.23453745e-01
    -2.36596853e-01 -3.08178812e-01 -2.49761477e-01 -3.60660046e-01
     6.22057132e-02 -2.62168497e-01]
   [-6.05155230e-01  2.55635660e-02 -1.60387512e-02  1.30503327e-01
    -9.74272788e-02 -1.81674272e-01 -1.25876501e-01 -1.74137488e-01
    -6.76220655e-02 -3.64214808e-01  3.33890826e-01 -2.76104480e-01
     7.74224177e-02 -1.55938774e-01  1.94641605e-01 -5.87676316e-02
     2.09209666e-01 -5.42815506e-01  1.57939523e-01 -4.97839570e-01
     7.81512819e-03  5.32636158e-02  2.34940946e-01 -6.62073940e-02
     8.99739563e-02 -1.76772079e-03 -6.11847676e-02 -2.38715023e-01
     1.17083691e-01 -8.63094449e-01]]

  [[ 6.57722056e-02  1.31434202e-02 -1.62593231e-01  1.95573270e-01
     2.82170087e-01 -3.94208759e-01 -4.88547236e-02 -6.88307762e-01
     4.71941143e-01  3.14957835e-02  4.31009419e-02 -4.02139455e-01
     2.43028834e-01 -7.03977719e-02  2.24176645e-01 -1.31464964e-02
     1.00843169e-01  3.22658896e-01  1.97211310e-01 -4.94544148e-01
     3.06718558e-01  5.95956743e-01  1.04494415e-01  6.83964342e-02
    -6.27292022e-02 -1.41467759e-02 -3.95275205e-01 -6.29489958e-01
     3.70383859e-01 -5.66169262e-01]
   [-3.80823225e-01 -3.47855687e-03  8.92089158e-02 -3.02410007e-01
     3.65028791e-02  9.87948328e-02  4.39077377e-01 -7.59903863e-02
     9.74233076e-02  8.30575153e-02 -1.65224401e-03 -1.26073182e-01
    -4.19232786e-01 -4.43886500e-03  4.53351766e-01  3.45001996e-01
     8.30679163e-02  1.97842605e-02 -6.17404699e-01 -6.90296352e-01
     3.50163192e-01 -3.20808515e-02  3.69262666e-01 -2.32199118e-01
    -4.65617388e-01  4.15492915e-02 -2.98583061e-01 -2.21809685e-01
    -7.47463480e-02 -2.48113535e-02]
   [-7.36337781e-01 -2.30185822e-01  4.32297051e-01  7.03988001e-02
     2.81221002e-01  3.87922108e-01  9.34432074e-02  8.38815141e-03
     2.66455561e-01 -2.17360646e-01  1.25658944e-01 -2.01075643e-01
     2.16551542e-01 -1.89456254e-01  9.94389206e-02  6.12886362e-02
    -1.47159159e-01 -3.66350472e-01 -1.75868362e-01  5.41217104e-02
     3.65568250e-01  2.06482217e-01  1.53186277e-01 -1.88458309e-01
    -7.07829118e-01 -3.88985962e-01 -2.31394202e-01 -4.83144760e-01
    -5.12293838e-02  6.99777380e-02]
   [-3.92673612e-01  2.78197229e-01  3.08197677e-01 -2.02989921e-01
     1.86472356e-01  3.99824589e-01  1.90041382e-02  4.46751453e-02
     1.64007440e-01 -2.25319475e-01  1.21686868e-01 -4.73919690e-01
    -3.49287093e-02 -3.74745429e-01  3.22502017e-01  3.85246947e-02
     1.12256728e-01 -5.37322640e-01 -9.91424993e-02 -1.99349955e-01
     1.73696309e-01  3.03953797e-01 -4.49385047e-02  2.34538138e-01
    -1.35353521e-01 -3.14730853e-01 -3.49968702e-01 -1.81440622e-01
    -1.69955298e-01 -4.93852824e-01]]

  [[ 1.92137063e-01 -5.01230620e-02  1.57512605e-01 -3.72399651e-02
     5.52019961e-02 -1.00797556e-01 -1.63146988e-01 -1.62540883e-01
     4.69463408e-01 -7.71620274e-02 -7.11266100e-02 -1.98899195e-01
     5.05937338e-01 -1.95787832e-01 -7.62403607e-02 -2.60751575e-01
    -1.19758144e-01 -2.47441739e-01  2.20932692e-01 -2.81036288e-01
     1.87675998e-01  6.82459891e-01  1.39838591e-01 -1.50058102e-02
     2.81780660e-01 -2.01530948e-01 -1.30344823e-01 -3.88899565e-01
     6.55728877e-01 -5.72875559e-01]
   [-3.74573052e-01  2.87811518e-01  2.87440121e-01 -1.04813814e-01
    -2.61611082e-02  4.63570684e-01  2.59527117e-01 -4.30638701e-01
    -2.02948734e-01  8.70281011e-02  4.64452729e-02  4.01396632e-01
     1.27934873e-01 -5.04161775e-01 -8.18183348e-02  1.11441374e-01
     3.43441188e-01 -1.46786436e-01  3.70936722e-01 -3.99084598e-01
     1.25871450e-01  7.23175883e-01  6.02943264e-03  4.91503961e-02
    -1.44041076e-01  1.31749555e-01 -5.98421454e-01 -6.77389920e-01
     2.40149781e-01 -4.64233786e-01]
   [-1.89892471e-01 -4.91076000e-02  1.76130667e-01 -1.52004138e-01
     5.54730184e-02  3.29995871e-01 -3.63414437e-01 -4.61487502e-01
     9.88478363e-02 -1.87372249e-02  8.66298154e-02  1.32822365e-01
     2.45145172e-01 -5.53294122e-01 -1.78489715e-01 -9.29855704e-02
     3.11139822e-01 -4.82152730e-01  2.11764708e-01 -4.80985284e-01
     4.13315386e-01  7.21212745e-01  5.76658435e-02  3.54043007e-01
    -4.53116477e-01 -2.89863814e-02 -5.50605476e-01 -4.84367818e-01
     5.32336570e-02 -5.15369773e-01]
   [ 5.88098764e-02 -3.30760062e-01  1.30063817e-01 -1.92481160e-01
     2.94947661e-02  3.47985812e-02 -5.89347780e-02 -1.10738315e-01
     5.33506215e-01 -3.11862659e-02  3.67974341e-01  2.29985729e-01
     2.75447339e-01 -4.65811938e-01 -1.57302409e-01 -1.94908798e-01
     9.93569493e-02 -2.07489535e-01  4.82438982e-01 -1.56979620e-01
     3.95415187e-01  2.55746484e-01  6.51271418e-02 -1.60985798e-01
    -4.08161908e-01  2.52720863e-02 -3.03147793e-01 -5.29331267e-01
     1.32135242e-01 -5.84514618e-01]]]]
Output:
[array([[ 2.96764431e+01,  6.71213636e+01,  4.12147522e+01,
         8.80817871e+01,  0.00000000e+00,  5.71460247e-01],
       [-3.21615562e+01, -9.73707771e+01,  9.98756332e+01,
         2.92041260e+02,  0.00000000e+00,  5.70315003e-01],
       [ 8.89563427e+01,  3.70605669e+01,  5.09798126e+01,
         8.26421356e+01,  0.00000000e+00,  5.69104195e-01],
       [ 9.41457806e+01, -7.19175529e+00,  3.57853241e+01,
         5.24285202e+01,  0.00000000e+00,  5.58063209e-01],
       [ 4.28698845e+01, -2.40819788e+01,  1.37774323e+02,
         7.89519424e+01,  0.00000000e+00,  5.47550738e-01],
       [ 2.85800934e+01, -6.98347092e+00,  4.42517776e+01,
         4.77319603e+01,  0.00000000e+00,  5.47133505e-01],
       [-1.33628119e+02, -5.29647608e+01,  3.56087402e+02,
         1.98829926e+02,  0.00000000e+00,  5.43465495e-01],
       [-1.85231886e+02,  6.12894917e+00,  4.57164886e+02,
         2.01300125e+02,  0.00000000e+00,  5.32889843e-01],
       [-2.42836571e+00, -5.06936073e+00,  4.33940964e+01,
         4.15106583e+01,  0.00000000e+00,  5.30327559e-01],
       [-1.14140511e+01, -6.97864151e+00,  1.12017715e+02,
         1.15563866e+02,  0.00000000e+00,  5.26842058e-01],
       [-3.90114021e+01, -6.95987358e+01,  1.76909531e+02,
         2.36302490e+02,  0.00000000e+00,  5.22900939e-01],
       [ 5.56148396e+01,  3.82673378e+01,  1.15388573e+02,
         7.98753891e+01,  0.00000000e+00,  5.11166930e-01],
       [ 5.90537605e+01, -4.38175201e-02,  4.08650742e+01,
         1.00900826e+02,  0.00000000e+00,  5.09416759e-01],
       [ 9.26818161e+01,  2.59415989e+01,  3.83797531e+01,
         4.62018967e+01,  0.00000000e+00,  5.06390572e-01],
       [-1.33476524e+01,  6.28817520e+01,  5.60995293e+01,
         3.73557320e+01,  0.00000000e+00,  5.03285825e-01],
       [ 2.41952095e+01,  2.58019638e+01,  1.15847824e+02,
         1.04931931e+02,  0.00000000e+00,  5.02097011e-01],
       [-8.45540600e+01, -4.70901871e+01,  3.88443512e+02,
         1.30149155e+02,  0.00000000e+00,  4.99244571e-01],
       [ 5.51724272e+01, -1.21401978e+01,  4.88548203e+01,
         5.81847343e+01,  0.00000000e+00,  4.99208510e-01],
       [ 2.67731628e+01,  4.70190964e+01,  4.38800697e+01,
         6.11597862e+01,  0.00000000e+00,  4.99130338e-01],
       [ 5.90452023e+01,  7.22521963e+01,  4.47204247e+01,
         7.70682144e+01,  0.00000000e+00,  4.87725526e-01],
       [-5.09665298e+00,  8.66552086e+01,  4.47083092e+01,
         5.00938148e+01,  0.00000000e+00,  4.87471879e-01],
       [-7.16910801e+01, -9.90322475e+01,  1.78954041e+02,
         3.57854156e+02,  0.00000000e+00,  4.82407838e-01],
       [ 4.23632050e+01,  3.10111876e+01,  1.47612823e+02,
         1.61478683e+02,  0.00000000e+00,  4.72343653e-01],
       [ 3.07912016e+01, -1.98677206e+01,  9.15598984e+01,
         1.28907120e+02,  0.00000000e+00,  4.65945780e-01],
       [ 1.38340187e+01, -2.77717943e+01,  1.99436432e+02,
         1.50603577e+02,  0.00000000e+00,  4.61094141e-01],
       [-4.66128864e+01,  4.81026802e+01,  3.23471252e+02,
         1.31864426e+02,  0.00000000e+00,  4.60835457e-01],
       [-2.78885593e+01,  5.88027296e+01,  9.51535492e+01,
         1.05160561e+02,  0.00000000e+00,  4.59454000e-01],
       [ 2.73949966e+01, -1.42290821e+01,  4.91180115e+01,
         1.31239243e+02,  0.00000000e+00,  4.59405571e-01],
       [ 4.01260080e+01, -3.55548096e+00,  1.42666443e+02,
         9.73470993e+01,  0.00000000e+00,  4.56575304e-01],
       [-5.63734522e+01,  8.74809933e+00,  1.43527649e+02,
         2.02355255e+02,  0.00000000e+00,  4.51208800e-01],
       [-2.68037128e+01, -3.53494921e+01,  9.27251740e+01,
         1.02599281e+02,  0.00000000e+00,  4.49199766e-01],
       [-9.25620651e+00,  1.45080452e+01,  5.30732574e+01,
         7.37756500e+01,  0.00000000e+00,  4.43896830e-01],
       [ 5.53823490e+01,  3.97307968e+01,  5.60463104e+01,
         8.16643219e+01,  0.00000000e+00,  4.42706317e-01],
       [-2.16355896e+01, -5.51588068e+01,  1.37371109e+02,
         1.36161880e+02,  0.00000000e+00,  4.25225556e-01],
       [ 9.12522335e+01,  8.17806873e+01,  4.35736275e+01,
         5.73684006e+01,  0.00000000e+00,  4.18055713e-01],
       [-3.36269302e+01,  3.73421211e+01,  1.06667816e+02,
         8.58196487e+01,  0.00000000e+00,  3.34409624e-01]])]
save json: output/output.json
Traceback (most recent call last):
  File "run.py", line 189, in <module>
    main()
  File "/home/wakisaka/blueoil/saved/det_20190326181434/export/save.ckpt-161/128x128/output/python/.venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/wakisaka/blueoil/saved/det_20190326181434/export/save.ckpt-161/128x128/output/python/.venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/wakisaka/blueoil/saved/det_20190326181434/export/save.ckpt-161/128x128/output/python/.venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wakisaka/blueoil/saved/det_20190326181434/export/save.ckpt-161/128x128/output/python/.venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 179, in main
    run_prediction(input_image, model, config_file)
  File "run.py", line 149, in run_prediction
    filename_images = image_from_json(json_obj, raw_images, image_files)
  File "/home/wakisaka/blueoil/saved/det_20190326181434/export/save.ckpt-161/128x128/output/python/lmnet/utils/output.py", line 293, in __call__
    filename_images = self._object_detection(json_results, raw_images, image_files)
  File "/home/wakisaka/blueoil/saved/det_20190326181434/export/save.ckpt-161/128x128/output/python/lmnet/utils/output.py", line 273, in _object_detection
    draw.rectangle(xy, outline=color)
  File "/home/wakisaka/blueoil/saved/det_20190326181434/export/save.ckpt-161/128x128/output/python/.venv/lib/python3.5/site-packages/PIL/ImageDraw.py", line 225, in rectangle
    ink, fill = self._getink(outline, fill)
  File "/home/wakisaka/blueoil/saved/det_20190326181434/export/save.ckpt-161/128x128/output/python/.venv/lib/python3.5/site-packages/PIL/ImageDraw.py", line 125, in _getink
    ink = self.draw.draw_ink(ink, self.mode)
SystemError: new style getargs format but argument is not a tuple
```

**Comment by ruimashita** [comment]
@iizukak 
I found the reason of error `draw.rectangle()` and `draw.text()` need tuple color parameter,  but currently it is list.
