### ISSUE TITLE
Cannot re-training when existing experiment ID is specified

### ISSUE THREAD

**Issue by hadusam** [blue-oil/blueoil#245]
```
masuda@leapmind-server-24:~/Project/blueoil$ ./blueoil.sh train tests/config/caltech101_classification.yml ./saved caltech101_classification_20190424165139
#### Run training (caltech101_classification_20190424165139) ####
Traceback (most recent call last):
  File "blueoil/blueoil_train.py", line 69, in <module>
    main()
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "blueoil/blueoil_train.py", line 65, in main
    run(config_file, experiment_id)
  File "blueoil/blueoil_train.py", line 31, in run
    save_config_file(blueoil_config_file, experiment_dir)
  File "blueoil/blueoil_train.py", line 46, in save_config_file
    os.path.join(dest_dir, 'blueoil_config.yaml')
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 474, in copy
    copy_v2(oldpath, newpath, overwrite)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 492, in copy_v2
    compat.as_bytes(src), compat.as_bytes(dst), overwrite, status)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AlreadyExistsError: file already exists
ERROR: Training exited with a non-zero status
```
Saving configuration file to `experiment_dir` fails if file already exists.
Now, we don't have a method of managing a re-trained config, so it should keep the latest config, I think.
Before #223 , it used `shutil.copyfile`,and it was overwriting config files.

https://github.com/blue-oil/blueoil/blob/5f679ee13283ff54ad336c79b9adf1250beca36a/blueoil/blueoil_train.py#L40-L47

https://github.com/blue-oil/blueoil/blob/5f679ee13283ff54ad336c79b9adf1250beca36a/lmnet/lmnet/utils/config.py#L274-L277

So, need to add `overwrite=True` to `gfile.Copy` to overwrite.
https://www.tensorflow.org/api_docs/python/tf/gfile/Copy

**Comment by hadusam** [comment]
Also, need tests for re-training
