### ISSUE TITLE
Bump up docker base image to Ubuntu bionic

### ISSUE THREAD

**Issue by primenumber** [blue-oil/blueoil#592]
What prevent it?

- DE10-Nano glibc version, will be resolved by new OS image

**Comment by hadusam** [comment]
This is a sample error log run  on `Ubuntu16.04 DE10-Nano` using binary converted by `Ubuntu 18.04 docker base image`.
```
[2019-07-30T06:04:51Z] ---begining of stderr---
  | [2019-07-30T06:04:51Z] Traceback (most recent call last):
  | [2019-07-30T06:04:51Z]   File "testing_code.py", line 24, in <module>
  | [2019-07-30T06:04:51Z]     print(t.run_library('./lib_arm_fpga.so', './000_images_placeholder:0.npy', './337_output:0.npy'))
  | [2019-07-30T06:04:51Z]   File "testing_code.py", line 10, in run_library
  | [2019-07-30T06:04:51Z]     nn.load(library)
  | [2019-07-30T06:04:51Z]   File "/root/automated_testing/nnlib.py", line 29, in load
  | [2019-07-30T06:04:51Z]     self.lib = ct.cdll.LoadLibrary(libpath)
  | [2019-07-30T06:04:51Z]   File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
  | [2019-07-30T06:04:51Z]     return self._dlltype(name)
  | [2019-07-30T06:04:51Z]   File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
  | [2019-07-30T06:04:51Z]     self._handle = _dlopen(self._name, mode)
  | [2019-07-30T06:04:51Z] OSError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./lib_arm_fpga.so)
  | [2019-07-30T06:04:51Z]
  | [2019-07-30T06:04:51Z] ---end of stderr---
```
Ref https://buildkite.com/blueoil/dlk-test/builds/55#7622fea2-61fc-4f7d-9ac0-49aa5016f5f1
