### ISSUE TITLE
Fix image_size_question in blueoil/cmd/main.py

### ISSUE THREAD

**Issue by yd8534976** [blue-oil/blueoil#645]
```
? your model name ():  dsa
? choose task type  classification
? choose network  LmnetV1Quantize
? choose dataset format  Caltech101
? training dataset path:  dsad
? set validation dataset? (if answer no, the dataset will be separated for training and validation by 9:1 ratio.)  no
? batch size (integer):  10
Traceback (most recent call last):
  File "blueoil/cmd/main.py", line 162, in <module>
    main()
  File "/home/yang/.conda/envs/tf_gpu/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/yang/.conda/envs/tf_gpu/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/yang/.conda/envs/tf_gpu/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yang/.conda/envs/tf_gpu/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yang/.conda/envs/tf_gpu/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "blueoil/cmd/main.py", line 42, in init
    blueoil_config = ask_questions()
  File "/home/yang/pr_single/blueoil/blueoil/cmd/init.py", line 316, in ask_questions
    image_size = prompt(image_size_question)
  File "/home/yang/pr_single/blueoil/blueoil/cmd/init.py", line 171, in prompt
    answers = whaaaaat.prompt(question)
  File "/home/yang/.conda/envs/tf_gpu/lib/python3.7/site-packages/whaaaaat/prompt.py", line 57, in prompt
    application = getattr(prompts, type).question(message, **_kwargs)
  File "/home/yang/.conda/envs/tf_gpu/lib/python3.7/site-packages/whaaaaat/prompts/input.py", line 20, in question
    if issubclass(validate_prompt, Validator):
  File "/home/yang/.conda/envs/tf_gpu/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

**Comment by yd8534976** [comment]
conda version python may be the reason for this issue.
