### ISSUE TITLE
The configuration file cannot be read when running lmnet with GKE.

### ISSUE THREAD

**Issue by odoku** [blue-oil/blueoil#676]
```
Traceback (most recent call last):
  File "lmnet/executor/train.py", line 411, in <module>
    main()
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "lmnet/executor/train.py", line 407, in main
    run(network, dataset, config_file, experiment_id, recreate)
  File "lmnet/executor/train.py", line 352, in run
    config = config_util.load(config_file)
  File "/home/blueoil/lmnet/lmnet/utils/config.py", line 117, in load
    config = loader(os.path.abspath(config_file))
  File "/home/blueoil/lmnet/lmnet/utils/config.py", line 125, in _load_py
    config_module = module_loader.load_module(config_file)
  File "/home/blueoil/lmnet/lmnet/utils/module_loader.py", line 34, in load_module
    raise ValueError("Module loading error. {} is not exists.".format(module_file_path))
ValueError: Module loading error. /home/blueoil/gs:/bucket-name/path/to/config.py is not exists.
```

One of the causes of the error is converting the path of the configuration file to an absolute path.

https://github.com/blue-oil/blueoil/blob/6d1f006b954ef5e3f88e7be62fd8c61193ff323d/lmnet/lmnet/utils/config.py#L117

Also, the process of reading the configuration file is not compatible with the cloud.

https://github.com/blue-oil/blueoil/blob/6d1f006b954ef5e3f88e7be62fd8c61193ff323d/lmnet/lmnet/utils/config.py#L124-L131

It works if you stop converting to an absolute path and modify the reading of the configuration file as follows.

```python
def load(config_file):
    ...

    config = loader(config_file)

    check_config(config)

    return config
```

```python
def _load_py(config_file):
    config = {}
    with gfile.GFile(config_file) as fp:
        source = fp.read()
        exec(source, globals(), config)

    # use only upper key.
    return EasyDict({
        key: value
        for key, value in config.items()
        if key.isupper()
    })
```

**Comment by Joeper214** [comment]
Fixed with https://github.com/blue-oil/blueoil/pull/678
