### ISSUE TITLE
Error message when failed to load config does not user-friendly

### ISSUE THREAD

**Issue by suttang** [blue-oil/blueoil#906]
When I run blueoil command and there is no config file in a specific directory, I got a non-user-friendly error message like below.

I think the better message is like `there is no config file` or `config file not found`, not `TypeError: expected str, bytes or os.PathLike object, not NoneType`

```
$ docker run --rm -it -e CUDA_VISIBLE_DEVICES=-1 -v $(pwd)/outputs:/home/blueoil/outputs blueoil_suttang:v0.16.0-111-ged7676b /bin/bash -c "cd lmnet && python executor/export.py -c /home/blueoil/outputs/dafnet/config.py -i dafnet"

Traceback (most recent call last):
  File "executor/export.py", line 237, in <module>
    main()
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "executor/export.py", line 233, in main
    run(experiment_id, restore_path, image_size, image, config_file)
  File "executor/export.py", line 167, in run
    config = config_util.load_from_experiment()
  File "/home/blueoil/lmnet/lmnet/utils/config.py", line 263, in load_from_experiment
    return load(config_file)
  File "/home/blueoil/lmnet/lmnet/utils/config.py", line 109, in load
    filename, file_extension = os.path.splitext(config_file)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/posixpath.py", line 120, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by tfujiwar** [comment]
Fixed in #943
